### ISSUE TITLE
primer_efficiency KeyError

### ISSUE THREAD

**Issue by rturba** [gjeunen/reference_database_creator#33] opened 2023-09-23 01:28 UTC
> Based on the error it seems that the seqID `AF402623` is in the input file, but cannot be found in the original raw sequencing file. Is this correct?
> 
> Best regards,
> Gert-Jan

_Originally posted by @gjeunen in https://github.com/gjeunen/reference_database_creator/issues/20#issuecomment-1535524214_

Hi, Gert-Jan

I'm using crabs v.0.1.1 installed with bioconda. I was trying to run the primer_efficiency module, but I'm getting the following error:

```
crabs visualization --method primer_efficiency --input input.tsv --fwd TYGTGCCAGCNRCCGCGGTYA --rev ATAGTRGGGTATCTAATCCYAGT --fwd_name 12S-V5-F --rev_name 12S-V5-R --raw_file crabs_vertDB_v2.fasta --tax_group Rodentia --output rodentia.fasta

Traceback (most recent call last):
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 1372, in <module>
    main()
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 1369, in main
    args.func(args)
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 929, in visualization
    orig = str(raw_dict[id])
KeyError: 'TACGATAAACCTAAACTAATAATTATACGGCGTAAGGCGTGTAAAAAGACTTAACACCAATAGGATAGAAAACGGCCCCTTAAGTAAAATTTTTATGGCCCCCATAAAATCAATAACGAAAATATTCCTAACAAACTTGATACACGAAAGCTAAGGCCCAA'
```

Based on your comment above to a similar issue, I've checked to see if this sequence was in my raw file (the one I've used for the insilico PCR), and it is. Any insights on why this might be happening?

Thanks in advance!
Rachel

**Comment by gjeunen** [comment] 2023-09-23 21:34
Hello Rachel,

Thank you for posting your error.

I'm wondering if there is an issue with the file format. The `KeyError` message you see should output a sequence ID, not the sequence itself. This leads me to believe that this sequence is on a separate line on its own, rather than at the end of the line behind all the metadata information. Could you check if this is the case please?

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-26 12:18
Hi Gert-Jan,

It seems that my clean.tsv file has only sequences in the seqID column, and the one that the code was complaining about is on line 8, but it doesn't look any more different than the rest of the data 🤔 So, was the file not supposed to look like that at all?

[12S-V5_insilico_tax_derep_clean.txt](https://github.com/gjeunen/reference_database_creator/files/12727380/12S-V5_insilico_tax_derep_clean.txt)

**Comment by gjeunen** [comment] 2023-09-26 19:46
Hello Rachel,

I'm not sure what happened, but in your file, the sequence is both at the beginning of the line and at the end. For CRABS, the sequence should only be present at the end of the line. The lines should start with the seqID (NCBI accession number). This is what is causing the error you are describing.

Was this file manually changed or did CRABS output this file?

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-26 22:21
It's a CRABS output after following the cleaning steps. This was done with v.0.1.1. Maybe there was a glitch somewhere in my pipeline? I can try rerunning everything with the newer version and check at this step if I'm still seeing the same output.

My reference database was downloaded using NSDPY because the cluster I'm working on does not allow ftp downloads (which has been a nightmare for this kind of thing!). But after downloading it I was able to edit it and import it in CRABS with no problems. I was even able to do the other steps... well, except the phylo module currently 😅

**Comment by gjeunen** [comment] 2023-09-26 22:53
I quickly wrote a python script to parse your document to remove the sequences in the beginning. Can you check the code on the new document. I suggest rerunning the full CRABS pipeline again, however, just in case other errors were encountered at other stages.

[12S-V5_insilico_tax_derep_clean_correct_format.txt](https://github.com/gjeunen/reference_database_creator/files/12732364/12S-V5_insilico_tax_derep_clean_correct_format.txt)

Apologies for all the issues you're encountering.

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-26 23:01
Thank you so much! There's nothing to apologize for. It's life with coding, right? Lol~~ And you've been super helpful and so quick. And honestly, best package I've tried so far :D I'm gonna try with the new file and get back to you asap!

**Comment by rturba** [comment] 2023-09-26 23:18
Whoa... strange, I'm still getting the same error:

```Traceback (most recent call last):
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 1458, in <module>
    main()
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 1455, in main
    args.func(args)
  File "/home/rachel.turba/envs/CRABS/bin/crabs", line 961, in visualization
    if abort == 'less':
UnboundLocalError: local variable 'abort' referenced before assignment```

**Comment by gjeunen** [comment] 2023-09-26 23:24
Can you please provide me the full code, CRABS version number, and the files used for the code (I think only the species.txt file, as I have the input file already)? No need to attach the nodes.dmp and names.dmp files.

I'll run it on my system to see if I can recreate the error and determine what is causing it.

**Comment by rturba** [comment] 2023-09-26 23:32
```crabs --version
0.1.7
crabs visualization --method phylo --input 12S-V5_insilico_tax_derep_clean_correct_format.tsv --level family --species species_list_PELD.txt --taxid taxonomy/nodes.dmp --name taxonomy/names.dmp```

[species_list_PELD.txt](https://github.com/gjeunen/reference_database_creator/files/12732513/species_list_PELD.txt)

Could it be related to other packages, since I had initially installed it via conda?

**Comment by rturba** [comment] 2023-09-26 23:42
Oh, wait! Sorry, I got confused with the different threads! I was running the phylo module (O/

**Comment by gjeunen** [comment] 2023-09-27 00:04
I managed to recreate the error message. The issue is that the file is still not formatted correctly. This was on oversight on my part, apologies. While I removed the sequence at the beginning of the line, the line is missing the accession number of the sequence at the start.

The structure of the file should be as the header states:

```
seqID (accession Number) \t taxid \t superkingdom \t phylum \t class \t order \t family \t genus \t species \t sequence
```

Originally, your structure was:

```
sequence \t taxid \t superkingdom \t phylum \t class \t order \t family \t genus \t species \t sequence
```

With the new file I provided to you, I just removed the sequence at the beginning without checking anything else:

```
taxid \t superkingdom \t phylum \t class \t order \t family \t genus \t species \t sequence
```

Without the info on the accession numbers, I cannot recreate the correct structure of the file. Unfortunately, this means that you'll have to rerun some of the code from where the formatting issues began. Could you paste the first couple of lines of the output files from the assign_tax, dereplicate, and seq_cleanup commands. Somewhere along here is most likely where the formatting error has occurred. Though still a bit perplexed with how this formatting issue has happened if files were not altered manually.

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-27 18:50
Sure thing!

Header of `assign_tax`:
```
CRABS:Saurogobio_punctatus	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
CRABS:Salmo_pallaryi	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

Header of `dereplicate`:
```
CRABS:Saurogobio_punctatus	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
CRABS:Salmo_pallaryi	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

Head of `seq_cleanup`:
```
seqID	taxid	superkingdom	phylum	class	order	family	genus	species	sequence
AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA	1771284.0	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA	2972643.0	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

So it really looks like the issue was on the last step. I haven't rerun it yet with the new version. I'll get back to you on that asap.

**Comment by gjeunen** [comment] 2023-09-27 20:04
I'm not sure if something went wrong during copy-pasting, but it seems that the information on each line in the `assign_tax` and `dereplicate` output files are occurring more than once, which is probably why the `seq_cleanup` output is incorrect as well. 

The structure of the `assign_tax` output file should be:

```
CRABS:Saurogobio_punctatus	1771284	Eukaryota	Chordata	Actinopteri	Cypriniformes	Gobionidae	Saurogobio	Saurogobio_punctatus	AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
CRABS:Salmo_pallaryi	2972643	Eukaryota	Chordata	Actinopteri	Salmoniformes	Salmonidae	Salmo	Salmo_pallaryi	TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

Can you rerun the `assign_tax` command and see if you can get the correct output format?

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-27 21:17
Hmmm... I've re-ran it and it's still giving me the same output structure.

```
CRABS:Saurogobio_punctatus      1771284 Eukaryota       Chordata        Actinopteri     Cypriniformes   Gobionidae      Saurogobio      Saurogobio_punctatus    AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA       1771284 Eukaryota       Chordata        Actinopteri     Cypriniformes   Gobionidae      Saurogobio      Saurogobio_punctatus    AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA       1771284 Eukaryota       Chordata        Actinopteri     Cypriniformes   Gobionidae      Saurogobio      Saurogobio_punctatus    AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
CRABS:Salmo_pallaryi    2972643 Eukaryota       Chordata        Actinopteri     Salmoniformes   Salmonidae      Salmo   Salmo_pallaryi  TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA      2972643 Eukaryota       Chordata        Actinopteri     Salmoniformes   Salmonidae      Salmo   Salmo_pallaryi  TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA      2972643 Eukaryota       Chordata        Actinopteri     Salmoniformes   Salmonidae      Salmo   Salmo_pallaryi  TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

The command I used was:
`crabs assign_tax -i 12S/12S-V5_insilico_v2.fasta -o 12S/12S-V5_insilico_tax_v2.tsv -a taxonomy/nucl_gb.accession2taxid -t taxonomy/nodes.dmp -n taxonomy/names.dmp --missing 12S/12S-V5_missing_taxa.tsv`

This is what the header of my input file looks like:
```
>CRABS:Saurogobio_punctatus
AACGATAGGCCCCAGTTGATAATATCACGGCGTAAAGGGTGGTTAAGGAATATAGAATAATAAAGCCAAATGGCCCCCTGGCCGTCATACGCTTCTAGGTGTCCGAAGCCCAATCCCACGAAAGTAGCTTTAATATAACCGACCTGACCCCACGAAAGCTGAGGAACAA
>CRABS:Salmo_pallaryi
TACGAGAGACCCTAGTTGATAACTACCGGCGTAAAGAGTGGTTACGGAAAAATATTCAATAAAGCCGAACACCCCCTCAGCCGTCATACGCACCTGGGGGCACGAAGATCTACTGCGAAAGCAGCTTTAATTATGCCTGAACCCACGACAGCTACGACACAA
```

**Comment by gjeunen** [comment] 2023-09-27 21:58
Would it be possible to share the input file? I'll see if I can recreate the structure on my system.

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-27 23:09
Ofc!

[12S-V5_insilico_v2.txt](https://github.com/gjeunen/reference_database_creator/files/12743931/12S-V5_insilico_v2.txt)

**Comment by gjeunen** [comment] 2023-09-28 00:12
All sequences have the header `CRABS:species_name` or CRABS:others`. None of the sequences have an accession number associated with them? Some species also have more than one sequence assigned to them, while the header doesn't specify a unique identifier. Was the `db_import` function used to import the data into CRABS?

I'm sorry if you've already provided this information, but could you copy-paste the code you used from download or importing the data till the input file you just shared, as the shared file has a uncommon structure as well?

Best,
Gert-Jan

**Comment by gjeunen** [comment] 2023-09-28 19:46
Let's try to work on the accession numbers. I've changed the CRABS code in `--version 0.1.8` for the `db_import` function to allow for a left-hand side delimiter.

From the initially downloaded sequence file that were downloaded with NSDPY, can you please try and run the following code:

```
crabs db_import -i sequences.fasta -d "." -l "-" -s accession -o outfile.fasta
``` 

The output file should be a two line fasta file that looks like:

```
>NC_080528
ACGTCA
```

You can run the following command in the terminal to check:

```
head -n 2 outfile.fasta
```

I currently do not have access to a similarly structured file, so couldn't test the changes I made. Please let me know if this works and if it resolves the issue with downstream processing.

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-09-29 13:48
Where can I access the new version? 👀

**Comment by gjeunen** [comment] 2023-09-29 19:15
You can clone or pull the latest GitHub code to get access to the new functionality. These minor changes, especially when not tested properly in advance, won't be identified as a new official release. You can always check the version number by typing the following command in the Terminal: `crabs --version`.

Please let me know if this solution works for you.

Best regards,
Gert-Jan

**Comment by rturba** [comment] 2023-10-05 20:35
Hi Gert-Jan,

Sorry for the delay on this. I'm trying to do the `db_import`, but I think my file has some irregular headers because I keep getting the following error:

```
crabs-v8 db_import -i NSDPY_sequences_removed.fasta -d "." -l "-" -s accession -o crabs_vertDB_accessionID.fasta

checking correct formatting of accession numbers in NSDPY_sequences_removed.fasta
Traceback (most recent call last):
  File "/home/rachel.turba/bin/crabs-v8", line 1462, in <module>
    main()
  File "/home/rachel.turba/bin/crabs-v8", line 1459, in main
    args.func(args)
  File "/home/rachel.turba/bin/crabs-v8", line 153, in db_import
    incorrect_accession = check_accession(INPUT, OUTPUT, DELIM, LEFT)
  File "/home/rachel.turba/reference_database_creator/function/module_db_download.py", line 393, in check_accession
    acc = f'>{str(record.description.split(delimiter)[0].split(leftdelimiter)[1])}'
IndexError: list index out of range
```

I've tried to manually check my file and remove the headers that do not have the regular `accessionID.<int>` format, but I had no luck so far. If I repeat the code above with the pipe delimiter:

`crabs-v8 db_import -i NSDPY_sequences_removed.fasta -d "|" -l "-" -s accession -o crabs_vertDB_accessionID.fasta`

It works, but then it seems that it does not recognize the accessions with the `"."`, e.g. HQ287886.1. So`, I end up with only very few sequences in my final DB :(

I'm trying to think of a way to edit my headers... So, not much advance on my end!

I've noticed the link I've shared above is not working, so here it goes again: https://brpucrs-my.sharepoint.com/:t:/g/personal/rachel_paula_edu_pucrs_br/EVONT6bDFkhHpcYewsHWMtYBcZt2EKMa5FbpWUiZ71DUHg?e=iO5OOu

**Comment by rturba** [comment] 2023-10-05 21:40
YESSSSSS! I did it :D

Ran the `db_import` and the structure of the file is as expected above. I'll run the downstream steps and keep you updated.

**Comment by gjeunen** [comment] 2023-10-06 01:04
Perfect, great to hear :)

**Comment by rturba** [comment] 2023-10-06 14:28
Ok, so now as I'm trying to assign taxonomy, I get the following warning:

```
crabs-v8 assign_tax -i 12S/12S_insilico.fasta -o 12S/12S_insilico_tax.fasta -a taxonomy/nucl_gb.accession2taxid -t taxonomy/nodes.dmp -n taxonomy/names.dmp
srun: job 1190 queued and waiting for resources
srun: job 1190 has been allocated resources
 93%|█████████▎| 15212677/16336493 [00:00<00:00, 26821156.26it/s]
100%|██████████| 11940957675/11940957675 [04:34<00:00, 43553262.40it/s]
100%|██████████| 190376896/190376896 [00:06<00:00, 28398204.22it/s]
100%|██████████| 233985992/233985992 [00:06<00:00, 36386072.37it/s]

retrieving accession numbers from 12S/12S_insilico.fasta
found 93088 accession numbers in 12S/12S_insilico.fasta
reading taxonomy/nucl_gb.accession2taxid into memory
reading taxonomy/nodes.dmp into memory
reading taxonomy/names.dmp into memory
processed 0 entries in taxonomy/nucl_gb.accession2taxid
processed 2518096 entries in taxonomy/nodes.dmp
processed 2518096 entries in taxonomy/names.dmp
assigning a tax ID number to 93088 accession numbers from 12S/12S_insilico.fasta
did not find 93088 accession numbers in taxonomy/nucl_gb.accession2taxid
0 accession numbers resulted in 0 unique tax ID numbers
generating taxonomic lineages for 0 tax ID numbers
assigning a taxonomic lineage to 93088 accession numbers
written 0 entries to 12S/12S_insilico_tax.fasta
```

Have you ever seen an issue with reading the `nucl_gb.accession2taxid` file before?

**Comment by gjeunen** [comment] 2023-10-06 18:45
Hello,

Could you please provide the following info on the document:

`ls -ltr taxonomy/nucl_gb.accession2taxid` to determine the file size.
`head -n 10 taxonomy/nucl_gb.accession2taxid` to determine the file structure.

Thanks,
Gert-Jan

**Comment by rturba** [comment] 2023-10-06 21:11
Ofc!

```(CRABS) rachel.turba@pantanal:~/promata/crabs$ ls -ltr taxonomy/nucl_gb.accession2taxid
-rw-r--r-- 1 rachel.turba labgenoma 11940957675 Sep 19 16:12 taxonomy/nucl_gb.accession2taxid
(CRABS) rachel.turba@pantanal:~/promata/crabs$ head -n 10 taxonomy/nucl_gb.accession2taxid
accession       accession.version       taxid   gi
A00001  A00001.1        10641   58418
A00002  A00002.1        9913    2
A00003  A00003.1        9913    3
A00004  A00004.1        32630   57971
A00005  A00005.1        32630   57972
A00006  A00006.1        32630   57973
A00008  A00008.1        32630   57974
A00009  A00009.1        32630   57975
A00010  A00010.1        32630   57976
```

Maybe none of my accession IDs are in this file? That would be kind of wild... But I'm going check that too.

**Comment by rturba** [comment] 2023-10-06 21:18
Well, I did a test with just the 1st one 'NC_080528', and it did find it, so maybe it's not that!

**Comment by gjeunen** [comment] 2023-10-06 21:22
The `nuclear_gb.accession2taxid` is structured appropriately, so that would not cause an issue. Could you please provide the structure of the input file by printing out the first couple of lines `head -n 10 12S/12S_insilico.fasta`?

Sorry, haven't seen this bug before. So, we'll have to find out what's happening...

**Comment by rturba** [comment] 2023-10-06 23:22
Oh, I think I know what the problem might be. I've noticed that after running the `db_import` command, my header is formatted with 2 '>', e.g.:

```
>>NC_080528
GCTAGCGTAGCTT
```

Not sure why that is the case. My input is still the same:

```
>Saurogobio_punctatus-NC_080528.1 | 1771284 | cellular organisms, Eukaryota, Opisthokonta, Metazoa, Eumetazoa, Bilateria, Deuterostomia, Chordata, Craniata, Vertebrata, Gnathostomata, Teleostomi, Euteleostomi, Actinopterygii, Actinopteri, Neopterygii, Teleostei, Osteoglossocephalai, Clupeocephala, Otomorpha, Ostariophysi, Otophysi, Cypriniphysae, Cypriniformes, Cyprinoidei, Gobionidae, Gobioninae, Saurogobio | NC_080528.1 Saurogobio punctatus mitochondrion, complete genome
GCTAGCGTAGCTTAATATAAAGCATAACACTGAAGATGTTAAGATGAGCCCTAAGAAGCTCCGCATGCAC
```

I've ran it twice to see if it was a glitch, and indeed it creates the header with 2 '>'.

**Comment by gjeunen** [comment] 2023-10-07 03:43
Yes, that will cause the issue, as CRABS now assumes that your accession numbers are `>NC_080528`, rather than `NC_080528` and hence, no matches in accession numbers are found.

Can you please run the following command on your file. It should replace `>>` with `>`. 

```
awk '{sub(/>>/,">")}1' 12S/12S_insilico.fasta > 12S/12S_insilico_formatted.fasta
``` 

Please check if this fixes the formatting error on your file and see if you can successfully run the `assign_tax` command.

Thanks,
Gert-Jan

**Comment by rturba** [comment] 2023-10-07 22:25
Yay! I was able to finish running the `primer_efficiency` step. Just need to be careful about cleaning up the '>>' from my `db_import` output before running the rest of things.

Thank you so much for all the help! 😁👍

**Comment by gjeunen** [comment] 2023-10-08 21:18
Glad it all worked out in the end! :)

**Closed by gjeunen** 2023-10-08 21:18 UTC
